---
deployment:
  tasks:
    - export DEPLOYPATH=/home/alenu/public_html
    - export NODEPATH=/home/alenu/quiz-app
    - /bin/mkdir -p $DEPLOYPATH
    - /bin/mkdir -p $NODEPATH
    - /bin/mkdir -p $NODEPATH/tmp
    - /bin/rsync -a ./ $DEPLOYPATH/
    - /bin/rsync -a ./ $NODEPATH/
    - /bin/chmod 755 /home/alenu/public_html
    - /bin/chmod -R 755 $DEPLOYPATH/images
    - /bin/chmod 644 $DEPLOYPATH/*.html
    - /bin/chmod 644 $DEPLOYPATH/*.css
    - /bin/chmod 644 $DEPLOYPATH/*.js
    - /bin/chmod 644 $DEPLOYPATH/.htaccess
    - /bin/touch $NODEPATH/tmp/restart.txt
