---
deployment:
  tasks:
    - export DEPLOYPATH1=/home/alenu/public_html
    - export DEPLOYPATH2=/home/alenu/ale.nu.hemsida.eu
    - /bin/mkdir -p $DEPLOYPATH1
    - /bin/mkdir -p $DEPLOYPATH2
    - /bin/rsync -a ./ $DEPLOYPATH1/
    - /bin/rsync -a ./ $DEPLOYPATH2/
